ALTER TABLE [dbo].[ParameterDefine]
    ADD CONSTRAINT [PK_ParameterDefine] PRIMARY KEY CLUSTERED ([ParameterKey] ASC, [SettingType] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

